name: Lint Code Base

on:
  push:
    branches-ignore: [main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  sast:
      runs-on: windows-latest
          
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
          
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
          
        - name: Install Dependencies
          run: pip install bandit
          
        - name: Run Bandit
          run: bandit -r .   
  copy-file:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
        
            - name: Pushes test file
              uses: dmnemec/copy_file_to_another_repo_action@main
              env:
                API_TOKEN_GITHUB: ${{ secrets.PUSH_TOKEN }}
              with:
        
                source_file: 'myproject/.'
                destination_repo: 'AllanDza/CompMast_TEST'
                
        
                user_email: 'allanferns007@gmail.com'
                user_name: 'AllanDza'
                commit_message: 'successful push'        
