name: SAST Scan

on:
  push:
    branches:
      - main

jobs:
  sast:
    runs-on: windows-latest

    - name: Set Git identity
      run: |
        git config --global user.email "allanferns08@gmail.com"
        git config --global user.name "AllanDza"
     

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: pip install bandit

      - name: Run Bandit
        run: bandit -r .
